services:
  auth-service:
    container_name: fatal-cinema-auth-service
    image: fatal-cinema/auth-service:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production.local
    networks:
      - fatal-cinema

networks:
  fatal-cinema:
    external: true
